In [1]:
import scraper as ws
import pandas as pd

In [2]:
df = ws.get_jobs('data scientist', 15, False, 7)

funciona
Progress: 0/15
Progress: 1/15
Progress: 2/15
Progress: 3/15
Progress: 4/15
Progress: 5/15
Progress: 6/15
Progress: 7/15
Progress: 8/15
Progress: 9/15
Progress: 10/15
Progress: 11/15
Progress: 12/15
Progress: 13/15
Progress: 14/15
Progress: 15/15
Scraping terminated before reaching target number of jobs. Needed 15, got 15.

In [3]:
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,Data Scientist (remote),Employer Provided Salary:$82K - $118K,Are you looking to make a difference in a pati...,3.6,AmerisourceBergen\n3.6,Remote,-1,-1,-1,-1,-1,-1,-1,-1
1,Associate Data Scientist,Employer Provided Salary:$72K - $114K,Location: Remote Work\nWork Type: Full Time Re...,3.8,Mutual of Omaha\n3.8,Remote,-1,-1,-1,-1,-1,-1,-1,-1
2,Data Scientist,Employer Provided Salary:$107K - $134K,Description\n\nAre you interested in making a ...,4.1,Corteva\n4.1,"Des Moines, IA",-1,-1,-1,-1,-1,-1,-1,-1
3,Data Scientist,-1,Greetings Everyone\n\nWho are we?\n\nFor the p...,3.8,Photon\n3.8,Washington State,-1,-1,-1,-1,-1,-1,-1,-1
4,Junior Data Scientist/Data Modeler,-1,Overview:\nLMI is seeking a skilled Data Scien...,4.2,Logistics Management Institute\n4.2,Remote,-1,-1,-1,-1,-1,-1,-1,-1